// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyA_SY78yZF2K0Fu7TjQYG4uuyGT7F1Jqhs',
//     appId: '1:1095955726795:web:8bb7b257731d730be8b64e',
//     messagingSenderId: '1095955726795',
//     projectId: 'asm-international-6620c',
//     authDomain: 'asm-international-6620c.firebaseapp.com',
//     storageBucket: 'asm-international-6620c.appspot.com',
//     measurementId: 'G-K6LBSCHTY4',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDhfY0HcNjvVnE83K8SKp7Xz8tdae73TuU',
//     appId: '1:1095955726795:android:8f3c31730405a61be8b64e',
//     messagingSenderId: '1095955726795',
//     projectId: 'asm-international-6620c',
//     storageBucket: 'asm-international-6620c.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBYtL2LCtCdB8M5b7NXn6KCnt5JtdfRrIY',
//     appId: '1:1095955726795:ios:0f8fc1aea55a029ee8b64e',
//     messagingSenderId: '1095955726795',
//     projectId: 'asm-international-6620c',
//     storageBucket: 'asm-international-6620c.appspot.com',
//     iosBundleId: 'asm.smpl.eventApp',
//   );
// }
